//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.Povezava {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Uporabnik", Namespace="http://schemas.datacontract.org/2004/07/simunovic_marko_WCF")]
    [System.SerializableAttribute()]
    public partial class Uporabnik : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool AdminField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GesloField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UporabniskoImeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Admin {
            get {
                return this.AdminField;
            }
            set {
                if ((this.AdminField.Equals(value) != true)) {
                    this.AdminField = value;
                    this.RaisePropertyChanged("Admin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Geslo {
            get {
                return this.GesloField;
            }
            set {
                if ((object.ReferenceEquals(this.GesloField, value) != true)) {
                    this.GesloField = value;
                    this.RaisePropertyChanged("Geslo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UporabniskoIme {
            get {
                return this.UporabniskoImeField;
            }
            set {
                if ((object.ReferenceEquals(this.UporabniskoImeField, value) != true)) {
                    this.UporabniskoImeField = value;
                    this.RaisePropertyChanged("UporabniskoIme");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Atlet", Namespace="http://schemas.datacontract.org/2004/07/simunovic_marko_WCF")]
    [System.SerializableAttribute()]
    public partial class Atlet : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DatumRojstvaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ImeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PriimekField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DatumRojstva {
            get {
                return this.DatumRojstvaField;
            }
            set {
                if ((this.DatumRojstvaField.Equals(value) != true)) {
                    this.DatumRojstvaField = value;
                    this.RaisePropertyChanged("DatumRojstva");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ime {
            get {
                return this.ImeField;
            }
            set {
                if ((object.ReferenceEquals(this.ImeField, value) != true)) {
                    this.ImeField = value;
                    this.RaisePropertyChanged("Ime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Priimek {
            get {
                return this.PriimekField;
            }
            set {
                if ((object.ReferenceEquals(this.PriimekField, value) != true)) {
                    this.PriimekField = value;
                    this.RaisePropertyChanged("Priimek");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Tekmovanje", Namespace="http://schemas.datacontract.org/2004/07/simunovic_marko_WCF")]
    [System.SerializableAttribute()]
    public partial class Tekmovanje : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DatumTekmovanjaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KrajField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NazivField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DatumTekmovanja {
            get {
                return this.DatumTekmovanjaField;
            }
            set {
                if ((this.DatumTekmovanjaField.Equals(value) != true)) {
                    this.DatumTekmovanjaField = value;
                    this.RaisePropertyChanged("DatumTekmovanja");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Kraj {
            get {
                return this.KrajField;
            }
            set {
                if ((object.ReferenceEquals(this.KrajField, value) != true)) {
                    this.KrajField = value;
                    this.RaisePropertyChanged("Kraj");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Naziv {
            get {
                return this.NazivField;
            }
            set {
                if ((object.ReferenceEquals(this.NazivField, value) != true)) {
                    this.NazivField = value;
                    this.RaisePropertyChanged("Naziv");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AtletTekmovanje", Namespace="http://schemas.datacontract.org/2004/07/simunovic_marko_WCF")]
    [System.SerializableAttribute()]
    public partial class AtletTekmovanje : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Client.Povezava.Atlet AtletField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RezultatField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Client.Povezava.Tekmovanje TekmovanjeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Client.Povezava.Atlet Atlet {
            get {
                return this.AtletField;
            }
            set {
                if ((object.ReferenceEquals(this.AtletField, value) != true)) {
                    this.AtletField = value;
                    this.RaisePropertyChanged("Atlet");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Rezultat {
            get {
                return this.RezultatField;
            }
            set {
                if ((object.ReferenceEquals(this.RezultatField, value) != true)) {
                    this.RezultatField = value;
                    this.RaisePropertyChanged("Rezultat");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Client.Povezava.Tekmovanje Tekmovanje {
            get {
                return this.TekmovanjeField;
            }
            set {
                if ((object.ReferenceEquals(this.TekmovanjeField, value) != true)) {
                    this.TekmovanjeField = value;
                    this.RaisePropertyChanged("Tekmovanje");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Povezava.IDeloSSeznami")]
    public interface IDeloSSeznami {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDeloSSeznami/UstvariUporabnika", ReplyAction="http://tempuri.org/IDeloSSeznami/UstvariUporabnikaResponse")]
        Client.Povezava.Uporabnik UstvariUporabnika(string uporabniskoIme, string geslo, bool admin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDeloSSeznami/UstvariUporabnika", ReplyAction="http://tempuri.org/IDeloSSeznami/UstvariUporabnikaResponse")]
        System.Threading.Tasks.Task<Client.Povezava.Uporabnik> UstvariUporabnikaAsync(string uporabniskoIme, string geslo, bool admin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDeloSSeznami/UstvariAtleta", ReplyAction="http://tempuri.org/IDeloSSeznami/UstvariAtletaResponse")]
        Client.Povezava.Atlet UstvariAtleta(string ime, string priimek, System.DateTime datumRojstva);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDeloSSeznami/UstvariAtleta", ReplyAction="http://tempuri.org/IDeloSSeznami/UstvariAtletaResponse")]
        System.Threading.Tasks.Task<Client.Povezava.Atlet> UstvariAtletaAsync(string ime, string priimek, System.DateTime datumRojstva);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDeloSSeznami/UstvariTekmovanje", ReplyAction="http://tempuri.org/IDeloSSeznami/UstvariTekmovanjeResponse")]
        Client.Povezava.Tekmovanje UstvariTekmovanje(string naziv, string kraj, System.DateTime datumTekmovanja);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDeloSSeznami/UstvariTekmovanje", ReplyAction="http://tempuri.org/IDeloSSeznami/UstvariTekmovanjeResponse")]
        System.Threading.Tasks.Task<Client.Povezava.Tekmovanje> UstvariTekmovanjeAsync(string naziv, string kraj, System.DateTime datumTekmovanja);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDeloSSeznami/UstvariTekmovanjeAtlet", ReplyAction="http://tempuri.org/IDeloSSeznami/UstvariTekmovanjeAtletResponse")]
        Client.Povezava.AtletTekmovanje UstvariTekmovanjeAtlet(Client.Povezava.Atlet atlet, Client.Povezava.Tekmovanje tekmovanje, string rezultat);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDeloSSeznami/UstvariTekmovanjeAtlet", ReplyAction="http://tempuri.org/IDeloSSeznami/UstvariTekmovanjeAtletResponse")]
        System.Threading.Tasks.Task<Client.Povezava.AtletTekmovanje> UstvariTekmovanjeAtletAsync(Client.Povezava.Atlet atlet, Client.Povezava.Tekmovanje tekmovanje, string rezultat);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDeloSSeznami/VpisUporabnika", ReplyAction="http://tempuri.org/IDeloSSeznami/VpisUporabnikaResponse")]
        Client.Povezava.Uporabnik VpisUporabnika(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDeloSSeznami/VpisUporabnika", ReplyAction="http://tempuri.org/IDeloSSeznami/VpisUporabnikaResponse")]
        System.Threading.Tasks.Task<Client.Povezava.Uporabnik> VpisUporabnikaAsync(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDeloSSeznami/VsiAtletiNaTekmovanju", ReplyAction="http://tempuri.org/IDeloSSeznami/VsiAtletiNaTekmovanjuResponse")]
        System.Collections.Generic.List<Client.Povezava.Atlet> VsiAtletiNaTekmovanju(string naziv);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDeloSSeznami/VsiAtletiNaTekmovanju", ReplyAction="http://tempuri.org/IDeloSSeznami/VsiAtletiNaTekmovanjuResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<Client.Povezava.Atlet>> VsiAtletiNaTekmovanjuAsync(string naziv);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDeloSSeznami/VsaTekmovanjaNaKaterihNastopAtlet", ReplyAction="http://tempuri.org/IDeloSSeznami/VsaTekmovanjaNaKaterihNastopAtletResponse")]
        System.Collections.Generic.List<Client.Povezava.Tekmovanje> VsaTekmovanjaNaKaterihNastopAtlet(string ime, string priimek);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDeloSSeznami/VsaTekmovanjaNaKaterihNastopAtlet", ReplyAction="http://tempuri.org/IDeloSSeznami/VsaTekmovanjaNaKaterihNastopAtletResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<Client.Povezava.Tekmovanje>> VsaTekmovanjaNaKaterihNastopAtletAsync(string ime, string priimek);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDeloSSeznami/PodrobnostiAtleta", ReplyAction="http://tempuri.org/IDeloSSeznami/PodrobnostiAtletaResponse")]
        Client.Povezava.Atlet PodrobnostiAtleta(string ime, string priimek);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDeloSSeznami/PodrobnostiAtleta", ReplyAction="http://tempuri.org/IDeloSSeznami/PodrobnostiAtletaResponse")]
        System.Threading.Tasks.Task<Client.Povezava.Atlet> PodrobnostiAtletaAsync(string ime, string priimek);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDeloSSeznami/TekmovanjeZNajvecAtleti", ReplyAction="http://tempuri.org/IDeloSSeznami/TekmovanjeZNajvecAtletiResponse")]
        Client.Povezava.Tekmovanje TekmovanjeZNajvecAtleti();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDeloSSeznami/TekmovanjeZNajvecAtleti", ReplyAction="http://tempuri.org/IDeloSSeznami/TekmovanjeZNajvecAtletiResponse")]
        System.Threading.Tasks.Task<Client.Povezava.Tekmovanje> TekmovanjeZNajvecAtletiAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDeloSSeznami/NajstarejsiAtlet", ReplyAction="http://tempuri.org/IDeloSSeznami/NajstarejsiAtletResponse")]
        Client.Povezava.Atlet NajstarejsiAtlet();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDeloSSeznami/NajstarejsiAtlet", ReplyAction="http://tempuri.org/IDeloSSeznami/NajstarejsiAtletResponse")]
        System.Threading.Tasks.Task<Client.Povezava.Atlet> NajstarejsiAtletAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDeloSSeznami/PovprecnaStarostAtleta", ReplyAction="http://tempuri.org/IDeloSSeznami/PovprecnaStarostAtletaResponse")]
        double PovprecnaStarostAtleta();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDeloSSeznami/PovprecnaStarostAtleta", ReplyAction="http://tempuri.org/IDeloSSeznami/PovprecnaStarostAtletaResponse")]
        System.Threading.Tasks.Task<double> PovprecnaStarostAtletaAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDeloSSeznami/VsiAtleti", ReplyAction="http://tempuri.org/IDeloSSeznami/VsiAtletiResponse")]
        System.Collections.Generic.List<Client.Povezava.Atlet> VsiAtleti();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDeloSSeznami/VsiAtleti", ReplyAction="http://tempuri.org/IDeloSSeznami/VsiAtletiResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<Client.Povezava.Atlet>> VsiAtletiAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDeloSSeznami/VsaTekmovanja", ReplyAction="http://tempuri.org/IDeloSSeznami/VsaTekmovanjaResponse")]
        System.Collections.Generic.List<Client.Povezava.Tekmovanje> VsaTekmovanja();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDeloSSeznami/VsaTekmovanja", ReplyAction="http://tempuri.org/IDeloSSeznami/VsaTekmovanjaResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<Client.Povezava.Tekmovanje>> VsaTekmovanjaAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDeloSSeznami/DodajAtleta", ReplyAction="http://tempuri.org/IDeloSSeznami/DodajAtletaResponse")]
        void DodajAtleta(string ime, string priimek, System.DateTime datumRojstva);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDeloSSeznami/DodajAtleta", ReplyAction="http://tempuri.org/IDeloSSeznami/DodajAtletaResponse")]
        System.Threading.Tasks.Task DodajAtletaAsync(string ime, string priimek, System.DateTime datumRojstva);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDeloSSeznami/VrniAtlete", ReplyAction="http://tempuri.org/IDeloSSeznami/VrniAtleteResponse")]
        System.Collections.Generic.List<Client.Povezava.Atlet> VrniAtlete();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDeloSSeznami/VrniAtlete", ReplyAction="http://tempuri.org/IDeloSSeznami/VrniAtleteResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<Client.Povezava.Atlet>> VrniAtleteAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDeloSSeznami/Uredi", ReplyAction="http://tempuri.org/IDeloSSeznami/UrediResponse")]
        bool Uredi(string tabela, string id, string imeStolpca, string vrednost);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDeloSSeznami/Uredi", ReplyAction="http://tempuri.org/IDeloSSeznami/UrediResponse")]
        System.Threading.Tasks.Task<bool> UrediAsync(string tabela, string id, string imeStolpca, string vrednost);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDeloSSeznamiChannel : Client.Povezava.IDeloSSeznami, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DeloSSeznamiClient : System.ServiceModel.ClientBase<Client.Povezava.IDeloSSeznami>, Client.Povezava.IDeloSSeznami {
        
        public DeloSSeznamiClient() {
        }
        
        public DeloSSeznamiClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DeloSSeznamiClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DeloSSeznamiClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DeloSSeznamiClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Client.Povezava.Uporabnik UstvariUporabnika(string uporabniskoIme, string geslo, bool admin) {
            return base.Channel.UstvariUporabnika(uporabniskoIme, geslo, admin);
        }
        
        public System.Threading.Tasks.Task<Client.Povezava.Uporabnik> UstvariUporabnikaAsync(string uporabniskoIme, string geslo, bool admin) {
            return base.Channel.UstvariUporabnikaAsync(uporabniskoIme, geslo, admin);
        }
        
        public Client.Povezava.Atlet UstvariAtleta(string ime, string priimek, System.DateTime datumRojstva) {
            return base.Channel.UstvariAtleta(ime, priimek, datumRojstva);
        }
        
        public System.Threading.Tasks.Task<Client.Povezava.Atlet> UstvariAtletaAsync(string ime, string priimek, System.DateTime datumRojstva) {
            return base.Channel.UstvariAtletaAsync(ime, priimek, datumRojstva);
        }
        
        public Client.Povezava.Tekmovanje UstvariTekmovanje(string naziv, string kraj, System.DateTime datumTekmovanja) {
            return base.Channel.UstvariTekmovanje(naziv, kraj, datumTekmovanja);
        }
        
        public System.Threading.Tasks.Task<Client.Povezava.Tekmovanje> UstvariTekmovanjeAsync(string naziv, string kraj, System.DateTime datumTekmovanja) {
            return base.Channel.UstvariTekmovanjeAsync(naziv, kraj, datumTekmovanja);
        }
        
        public Client.Povezava.AtletTekmovanje UstvariTekmovanjeAtlet(Client.Povezava.Atlet atlet, Client.Povezava.Tekmovanje tekmovanje, string rezultat) {
            return base.Channel.UstvariTekmovanjeAtlet(atlet, tekmovanje, rezultat);
        }
        
        public System.Threading.Tasks.Task<Client.Povezava.AtletTekmovanje> UstvariTekmovanjeAtletAsync(Client.Povezava.Atlet atlet, Client.Povezava.Tekmovanje tekmovanje, string rezultat) {
            return base.Channel.UstvariTekmovanjeAtletAsync(atlet, tekmovanje, rezultat);
        }
        
        public Client.Povezava.Uporabnik VpisUporabnika(string username, string password) {
            return base.Channel.VpisUporabnika(username, password);
        }
        
        public System.Threading.Tasks.Task<Client.Povezava.Uporabnik> VpisUporabnikaAsync(string username, string password) {
            return base.Channel.VpisUporabnikaAsync(username, password);
        }
        
        public System.Collections.Generic.List<Client.Povezava.Atlet> VsiAtletiNaTekmovanju(string naziv) {
            return base.Channel.VsiAtletiNaTekmovanju(naziv);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<Client.Povezava.Atlet>> VsiAtletiNaTekmovanjuAsync(string naziv) {
            return base.Channel.VsiAtletiNaTekmovanjuAsync(naziv);
        }
        
        public System.Collections.Generic.List<Client.Povezava.Tekmovanje> VsaTekmovanjaNaKaterihNastopAtlet(string ime, string priimek) {
            return base.Channel.VsaTekmovanjaNaKaterihNastopAtlet(ime, priimek);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<Client.Povezava.Tekmovanje>> VsaTekmovanjaNaKaterihNastopAtletAsync(string ime, string priimek) {
            return base.Channel.VsaTekmovanjaNaKaterihNastopAtletAsync(ime, priimek);
        }
        
        public Client.Povezava.Atlet PodrobnostiAtleta(string ime, string priimek) {
            return base.Channel.PodrobnostiAtleta(ime, priimek);
        }
        
        public System.Threading.Tasks.Task<Client.Povezava.Atlet> PodrobnostiAtletaAsync(string ime, string priimek) {
            return base.Channel.PodrobnostiAtletaAsync(ime, priimek);
        }
        
        public Client.Povezava.Tekmovanje TekmovanjeZNajvecAtleti() {
            return base.Channel.TekmovanjeZNajvecAtleti();
        }
        
        public System.Threading.Tasks.Task<Client.Povezava.Tekmovanje> TekmovanjeZNajvecAtletiAsync() {
            return base.Channel.TekmovanjeZNajvecAtletiAsync();
        }
        
        public Client.Povezava.Atlet NajstarejsiAtlet() {
            return base.Channel.NajstarejsiAtlet();
        }
        
        public System.Threading.Tasks.Task<Client.Povezava.Atlet> NajstarejsiAtletAsync() {
            return base.Channel.NajstarejsiAtletAsync();
        }
        
        public double PovprecnaStarostAtleta() {
            return base.Channel.PovprecnaStarostAtleta();
        }
        
        public System.Threading.Tasks.Task<double> PovprecnaStarostAtletaAsync() {
            return base.Channel.PovprecnaStarostAtletaAsync();
        }
        
        public System.Collections.Generic.List<Client.Povezava.Atlet> VsiAtleti() {
            return base.Channel.VsiAtleti();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<Client.Povezava.Atlet>> VsiAtletiAsync() {
            return base.Channel.VsiAtletiAsync();
        }
        
        public System.Collections.Generic.List<Client.Povezava.Tekmovanje> VsaTekmovanja() {
            return base.Channel.VsaTekmovanja();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<Client.Povezava.Tekmovanje>> VsaTekmovanjaAsync() {
            return base.Channel.VsaTekmovanjaAsync();
        }
        
        public void DodajAtleta(string ime, string priimek, System.DateTime datumRojstva) {
            base.Channel.DodajAtleta(ime, priimek, datumRojstva);
        }
        
        public System.Threading.Tasks.Task DodajAtletaAsync(string ime, string priimek, System.DateTime datumRojstva) {
            return base.Channel.DodajAtletaAsync(ime, priimek, datumRojstva);
        }
        
        public System.Collections.Generic.List<Client.Povezava.Atlet> VrniAtlete() {
            return base.Channel.VrniAtlete();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<Client.Povezava.Atlet>> VrniAtleteAsync() {
            return base.Channel.VrniAtleteAsync();
        }
        
        public bool Uredi(string tabela, string id, string imeStolpca, string vrednost) {
            return base.Channel.Uredi(tabela, id, imeStolpca, vrednost);
        }
        
        public System.Threading.Tasks.Task<bool> UrediAsync(string tabela, string id, string imeStolpca, string vrednost) {
            return base.Channel.UrediAsync(tabela, id, imeStolpca, vrednost);
        }
    }
}
